### ISSUE TITLE
Single click on the IMAGE icon in the browser

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#134]
What's the behaviour we're looking for when someone single-clicks the IMAGE icon in the browser? Right now it does nothing. @Sabrina-Knappe suggests adding instructions to it.

**Comment by Cybernide** [comment]
Quick research suggests that it should probably allow for quick options to be manipulated, maybe this is where people can specify their rendering options quickly here? @Sabrina-Knappe what do you think?

**Comment by jeffbl** [comment]
With the manifest V3 build being released today, it looks like left click on the IMAGE icon now brings up a little panel of all the options, seemingly due to an update in Chrome, and not any explicit action taken on our part. @Sabrina-Knappe is this cool with you? I haven't tested in anything other than Chrome, so don't know if this happens in other supported browsers as well?

Moving to Nov14 sprint since our hand is forced on this. If it is good and works appropriately in other browsers, this can be closed, since it is done. If not, we need to specify what needs to change.

**Comment by Cybernide** [comment]
This behaviour is consistent in Opera and Edge. I had suggested that options be available from this button before, so I am not unhappy with this change. 

The other thing that I had suggested was using it to gather a list of all the graphics on a single webpage that IMAGE could interact with, as NVDA also does something similar with the Elements List https://www.nvaccess.org/files/nvda/documentation/userGuide.html#ElementsList
I'm still open to testing this option out.

**Comment by jeffbl** [comment]
You mean you want t alist of all graphics on the page that IMAGE can handle, allowing the user to select? That will require design work, and potentially significant implementation time, so would need to be costed. If you're OK with current functionality in the popup for now, suggest closing this and making a new work item for the new feature of the list of graphics on the entire page. When making new work item, please ping me so I can comment. Thanks!

**Comment by Cybernide** [comment]
Actionable issue #283 . Closing @jeffbl
