### ISSUE TITLE
Allow access to graphic blob (entire request?) in info.ts

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-browser#147]
Currently, the only way for info.ts to have access to information in the request sent by the extension is for that information to be returned by the handler. That's not usually too bad, except when it comes to the base64 blob of the graphic. The graphic if not the entire request itself should be made available to renderers as needed, particularly for haptics renderers.

**Comment by JRegimbal** [comment]
Assigned to @jaydeepsingh25 for triage.

**Comment by jeffbl** [comment]
Brainstorm: This could potentially also give us a way to more efficiently do a nicer in-extension version of the visual debug tool (Shared-Reality-Lab/IMAGE-server#117), by just returning overlays of the drawn outlines for different preprocessors/segments, rather than complete images, which would likely be much smaller.

**Comment by jeffbl** [comment]
@jaydeepsingh25 We need an estimate on this since it would help the haply demo for CSUN. Ping me on gather to discuss. If this is not a large item, would love to have this in. @sriGanna / @rayanisran had some ideas on how to implement this, and seemed to think it might not be too intrusive/time consuming.
