### ISSUE TITLE
Brave: Extension developer mode doesn't show Haply options

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#237]
Still works in Chrome on Linux
In Brave on Linux, running latest extension build (https://github.com/Shared-Reality-Lab/IMAGE-server/issues/457)
In extension options, turn on developer mode, and see this:

![image](https://user-images.githubusercontent.com/2095406/176716124-30585f31-d003-48c0-9e94-093ca6ebcbf2.png)

EXPECT: Haply options should appear.

Unless we find similar behavior on another more common browser, not putting this in NFB milestone since Brave users probably few and far between, and only impacts haptics options, which would only impact our own demos at this point.

**Comment by jaydeepsingh25** [comment]
I believe this is expected behavior. The functionality was implemented as part of work-item https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/84, and thus the haply option should not come for browsers that do not support Web Serials. Brave and infact Firefox also does not support Web Serial API and hence the option is not visible on these browsers. @jeffbl please let me know if i need to revert this functionality? Otherwise this issue can be closed.

**Comment by jeffbl** [comment]
And, I think this might even be a dupe, since I got fooled on this before, since I forgot that Brave is different in this respect! Closing.

**Comment by jeffbl** [comment]
Bringing this back with the idea that it would be better to put in a string in this case, e.g., "Haply 2diy: Unavailable since this browser does not support Web Serial."

**Comment by jeffbl** [comment]
Given the upcoming focus on haptics in IMAGE, this is likely to be more important. @jaydeepsingh25 Possible to add to option panel refactoring / new functionality milestone?
