### ISSUE TITLE
Design an "IMAGE Elements list"

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#283]
See [browser #134](https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/134) for more context.

Users sometimes find it difficult to bring up graphics using the context menu or may find it difficult to know which webpage elements IMAGE can work on. We are also looking for a use for the single-click button for the extension.

Currently NVDA allows a user to press a hotkey combination to bring up a list of webpage elements. Given the trickiness of assigning hotkey combinations, we should investigate the utility of having the IMAGE icon give access to a list of graphics (photos, charts, and maps) that we can provide renderings for.

![image](https://user-images.githubusercontent.com/7490996/208523109-9067fede-ddc6-4c3c-9913-d3cc288f71c9.png)

Suggest implementing for a UI use study (aiming for February testing?)

**Comment by Cybernide** [comment]
Ping @jeffbl and @Sabrina-Knappe for comment

**Comment by jeffbl** [comment]
@Cybernide first we'd have to know that we can bring up that one-click menu easily on the platforms we support. From what I've seen:

1. by default (in Brave and Chrome anyway) that the icon does not appear by default, and you have "pin" it to get it on the bar at all. How will we get users to do this?
2. Once it is pinned, at least in Brave, it doesn't seem to be in the tab order, so it is not clear how someone would access the button. (Which means they are unlikely to get to options, either...although those are not currently all that useful for end users)

I think extensions can add custom hotkeys, so we could go that direction as well, but then that is a training thing as well.

Also, to be clear, we'd be able to list things that the user can request renderings for, but we don't currently have a mechanism to check whether or not a rendering can actually be created, since that depends on what the server can get. So we cannot list graphics/maps/charts "that we can provide renderings for" but rather "for which the user can request renderings".

Before we even ask Jaydeep to see if this is easily implementable or whether we'd want to mock it up first for testing, we need to figure out how this would realistically be triggered?

**Comment by Cybernide** [comment]
Agreed that the icon will likely be an issue if it doesn't appear and is not in tab order. Suggest hotkeys then. This [Stack Overflow](https://stackoverflow.com/questions/48293594/adding-keyboard-shortcuts-to-execute-chrome-extension) seems to suggest that it is possible to use Ctrl+Alt+any number key to do so. 

At the risk of cluttering the Context menu, we could make it a context menu item as well. Opinions?

**Comment by Cybernide** [comment]
@jaydeepsingh25 Can we (for now) implement a hotkey trigger to bring up something that looks like this?
Webpage content:
![image](https://user-images.githubusercontent.com/7490996/215895251-40753f8f-3bf0-4f8b-994c-7bf9c68f7dd9.png)
On trigger:
![image](https://user-images.githubusercontent.com/7490996/215895179-ad73887f-eb96-45c3-840e-fc259a6eddfd.png)

**Comment by jeffbl** [comment]
@Cybernide did you mean to assign this to Jaydeep for investigation? Either way, I'm moving this to Feb13 sprint.

**Comment by Cybernide** [comment]
Just waiting for input from Jaydeep on feasibility

**Comment by jeffbl** [comment]
@Cybernide if there is more technical investigation that needs to be done by jaydeep, please specify here. Otherwise, this would need a full design pass before going to implementation. Is this something that should be prototyped/investigated before design and implementation? Many other things to consider in addition to what Jaydeep indicates above, I expect, since even getting useful names for the graphics might be difficult? This probably needs some initial design thinking, then a sit-down session to flesh it out and get to something implementable. Before going through that, is there a way to determine whether users are likely to actually use this? e.g., How do they discover the hotkey combination? Is that something that will differ between screen readers?

**Comment by Cybernide** [comment]
> - Do we display different buttons, with a button for each image/chart/map
List elements would be the most familiar to users of NVDA
> - Do we also need to re-render maps/graphics on popup UI, or just the button is enough?
Just a selectable list item is enough for now
> - What if there are multiple images/maps/charts on a page. User may not get to know for what he is actually getting the rendering for? eg: https://www.worldometers.info/coronavirus/coronavirus-cases/
Yes, this one is difficult because ideally there would be a map or chart title (alt-text for the photo?) For now, I might go for some kind of page structure.

I'll get you another wireframe ASAP

**Comment by jeffbl** [comment]
moving to backlog in absence of story.

**Comment by Cybernide** [comment]
This issue has evolved into a much larger UI overhaul. Closing
