### ISSUE TITLE
STORY: As the 2diy integration developer, I want to port a minimal version of the existing texture/force feedback demo into the extension, so that we know whether it feasible.

### ISSUE THREAD

**Issue by jaydeepsingh25** [Shared-Reality-Lab/IMAGE-browser#337]
The integration of 2diy3g is completed in #321, still the extension does not provide good user experience with the 2diy3g device. This work item includes enhancements to improve the accuracy and user experience of the haptics renderings returned.

**Comment by jeffbl** [comment]
@jaydeepsingh25 great you're getting this working browser. Original title of this story:

STORY: As the 2diy integration developer, I want to improve the user experience and accuracy of renderings when using 2diy3g.

After discussions, I've edited to be:

STORY: As the 2diy integration developer, I want to port a minimal version of the existing texture/force feedback demo into the extension, so that we know whether it feasible

This means, at minimum, having a hard-coded version of Juliette's four circle demo running in the extension, with the end-user experience comparable to running Juliette's demo outside the extension with the same parameters set.

OPTIONAL: Adding Juliette's visualization

OPTIONAL: ability to adjust the parameters within the extension (rather than hard-coding)

This is effectively throw-away work where the ONLY purpose to to make the call on whether we can feasibly create experiences within the extension, or if there are fundamental limitations that will prevent this.

Moving to Oct23 sprint for ongoing implementation.

**Comment by jeffbl** [comment]
Great progress given your report from sprint meeting this week! Sounded like there were still a few issues remaining before this can be closed, so I'm moving to the Dec21 sprint.
