### ISSUE TITLE
Implement new UI options for activating IMAGE extension to photographs

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#390]
Investigate
- [ ] Toggle buttons using a setting in the options panel. @jaydeepsingh25 let me know if you need wireframes.
- [ ] Toggle buttons using a hotkey.
- [ ] Activate IMAGE by using a hotkey directly on a selected photo/map/chart.

@jaydeepsingh25 is it possible to use Ctrl+I+_<another key>_ for either of the latter two options? This might be the deciding factor for how we do this.

@jeffbl for triage

> Based on the very early results of UI testing, the number of embeddings can be overwhelming to BLV as well. In case of TL;DR, the proposed solutions for now are to:
> 1 toggle buttons on and off with a hotkey and/or setting in the options panel.
> 2 activate IMAGE by directly tabbing onto a photo/map/chart and using a hotkey on the selected item. (If possible, there should be a sound that plays when activation is attempted on an invalid item.)
> 
> I suggest we try having both options available for now.
> 
> I will investigate hotkey options, but @jaydeepsingh25 should feel free to use something temporary in the meantime for testing out implementation.
> 
> ---
> 
> Thus far, participants are lukewarm about prioritizing discovery with buttons or new interface items at best. The buttons do break up the flow of navigation to them. Their argument is "well of course I know that I have this extension, I don't need a button to tell me that I can use it on things." When we start testing on maps and charts, I'll have a better idea of whether buttons should be scrapped or kept.
> 
>  

 _Originally posted by @Cybernide in [#384](https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/384#issuecomment-2289481725)_

**Comment by jeffbl** [comment]
@Cybernide I believe all aspects of this work item are already covered in #387 (hotkey to trigger IMAGE on current photo, and already implemented in nightly), and #388 (option to turn buttons on/off). The only new addition is another hotkey specifically for triggering the buttons on/off item, which I've noted in #388 by referring to this item.

@Cybernide I've marked this as "duplicate" since I'm not sure what else it adds, beyond tweaks to existing work items. If you agree, please close. If not, please either update existing items, or modify this one/log new for specific issues.

@cyan RE: hotkey directly on a selected map or chart (and not just a photo) needs to be vetted for feasibility - is there a tab stop on these such that we would be able to do this? For example, on [this chart](https://etherscan.io/chart/etherprice), if I tab through, it seems to jump from the end date field directly to our current button, implying there is no specific tab stop for the chart as a whole? If this needs to be investigated, should be a separate issue, since I'm not sure it is possible, but I haven't tried it for maps.

@Cybernide to test #387, should we push a new test version from the nightly?

**Comment by Cybernide** [comment]
I missed these updates last week, apologies. I'll break out the last item and follow up with the rest.
