### ISSUE TITLE
Browser extension Chrome Web Store entry updates

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#74]
We are submitting the extension with only the basic information and graphics. Putting a list here of things to revisit for beta, when we make it more public:

- [x] Update description to include new functionality (e.g., haptics, local files, settings page, etc.)
- [x] Reword the "description" in the uploaded ZIP file that says something like "very, very alpha"
- [x] Upload changes

**Comment by Sabrina-Knappe** [comment]
This has been on the backburner for me because it isn't directly related to my thesis work, @Clarisa1999 what specifically do you need from me for this.

**Comment by jeffbl** [comment]
This needs a broader look from the UI/UX team, to figure out how to best take advantage of this landing page. Assigning to @Cybernide to determine who will do that, before assignment to Clarissa with specific text/wireframes.

**Comment by jeffbl** [comment]
localized/global - I don't know what this means (just guesses about screenshots in different languages), and we did not definitively figure it out when we were doing the original submission. You'll need to sync up directly with @Clarisa1999 to understand all the items completely.

**Comment by Cybernide** [comment]
For posterity, here's the text, some parts rearranged, instructions added, settings page and haptic devices mentioned:
_Extension for the McGill IMAGE project. Currently in beta!
Making internet graphics accessible through rich audio and (in a future release) touch!

Have you ever wanted to hear a photograph or pie chart, and not just a description of what is in it? IMAGE (Internet Multimodal Access to Graphical Exploration) adds a new item to your browser’s context menu when you activate it on a graphic such as a photograph, on any webpage you visit. The goal is to provide people who are blind or have low vision with a new and useful experience of internet graphics that goes beyond automatically generating alt tags. 

Once you have added the extension to your browser, all you have to do is tab to a graphic on any website, and similarly to how you would open a context menu on a link to bookmark it, open a context menu on the graphic and select “Get IMAGE Rendering.” The graphic is sent to a server that creates a custom audio rendering, and if you are wearing headphones, uses “spatialized audio” so that you hear different parts of the graphic all around you, rendered as sounds. In addition, if you go to the extension's setting page, you can enable haptic devices such as the Haply and the Dot Pad in order to explore graphics with your sense of touch.

This release is a beta version of IMAGE, and does not work well on all graphics. To get started, we recommend visiting our tutorial page at https://image.a11y.mcgill.ca/pages/alph_tut.html

IMAGE is carried out by McGill University's Shared Reality Lab (SRL) [1], in strategic partnership with Gateway Navigation CCC Ltd [2] and the Canadian Council of the Blind (CCB) [3]. The project is funded by Innovation Science Economic Development Canada through the Assistive Technology Program. The motivation for this project is to improve the access to internet graphics for people who are blind or partially sighted.

For more information about how we handle your data, please see:
https://image.a11y.mcgill.ca/pages/policies.html

For technical issues, please contact image@cim.mcgill.ca.
For other inquiries, please contact image@gnc3.com.

ABOUT US

[1] The Shared Reality Lab, in McGill University’s Department of
Electrical and Computer Engineering, works with audio, video, and
haptic technologies, building systems that leverage their capabilities
to facilitate and enrich both human-computer and computer-mediated
human-human interaction. http://srl.mcgill.ca

[2] Gateway Navigation CCC Limited is a unique social enterprise
bringing together social innovation and for-profit sustainability.
Founded in 2017 by individuals and organizations including the
Canadian Council of the Blind (CCB). Sharing a lived experience in
disability and a passion to make a difference in our communities. Our
social and business objective is to create a more accessible and
inclusive world through applying human centred design in the use of
inclusive audio-based (digital) augmented reality networks, while
promoting training and employment opportunities for people with
disabilities in this rapidly developing technology sector.
https://gnc3.com/

[3] The Canadian Council of the Blind (CCB) is the largest
member-based consumer organization of persons who are blind,
deaf-blind, or partially sighted in Canada. https://ccbnational.net/_

**Comment by Cybernide** [comment]
I'm going to write up new descriptions for the renderings before taking screenshots (see #126 )

**Comment by Cybernide** [comment]
I've made browser #127 and #123 and #129 separate issues, as I think for restricted beta, changing the wording on the extension store page is good enough. The rest of these are waiting on separate items that I don't think will be done until at least open beta. Editing checklist above to reflect these changes.

**Comment by Cybernide** [comment]
Uploaded.
