### ISSUE TITLE
Extension does not work on flickr site

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#82]
Brave Browser on Ubuntu
Extension 0.1.0

Go to page: https://www.flickr.com/groups/allfreepictures/
Right click any thumbnail.
Right Click -> IMAGE extension -> Get IMAGE rendering

NOTE: Nothing happens, no error, no popup
EXPECT: error, or list of renderings

Click on one of the thumbnails to get to a page like:
https://www.flickr.com/photos/string_bass_dave/51729207037/in/pool-allfreepictures/

Right Click -> IMAGE extension -> Get IMAGE rendering
NOTE: No IMAGE extension menu
EXPECT: Menu to get IMAGE rendering

If this is protection of some kind, or unique to this site, not a big deal (but should still give an error if the menu is present and something goes wrong!), but would be good to at least understand the constraint here so we can better understand and explain where IMAGE will actually work.

**Comment by hongyec** [comment]
Hi @jeffbl @jaydeepsingh25, I think it's not unique to flickr site. When I try google image, it's the same issue. 

Go to page: https://www.google.com/search?q=image&oq=image&aqs=chrome..69i57j35i39l2j0i433i512j46i175i199i512j46i131i433i512j0i512j0i433i512j46i131i199i291i433j0i433i512.535j0j15&sourceid=chrome&ie=UTF-8
Right click any thumbnail.
Right Click -> IMAGE extension -> Get IMAGE rendering

NOTE: Nothing happens, no error, no popup
EXPECT: error, or list of renderings

**Comment by jaydeepsingh25** [comment]
Initial investigation results:

- for images on flickr site: It does not work because thumbnails are not an image tag, it is a "div" element with a "background-image" css property. The context menu appears because there is a "link" inside div. (and currently, we display context menu for both - "images" and "link"). May be we need to remove the context menu option for "links". - fix in PR https://github.com/Shared-Reality-Lab/IMAGE-browser/pull/218
- for images in google search results: it does not work  because the src attribute of the images is not a valid a valid url, instead it is a binary image data. A simple UI check on the extension should solve this. @hongyec will add this check

**Comment by jaydeepsingh25** [comment]
closing this issue as it is fixed by https://github.com/Shared-Reality-Lab/IMAGE-browser/pull/218. For flickr site, the context menu will no longer appear as the thumbnails are not "image" tags. These images are added by css.
Created issue https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/220 to support images in google image search results.
